language: python
python:
  - "3.7.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements/travis.txt"
# # command to run tests, e.g. python setup.py test
services:
  - postgresql

addons:
    apt:
      packages:
        - postgresql-11
        - postgresql-11-postgis-2.5
        - postgresql-11-postgis-2.5-scripts

before_script:
  - psql -c 'create database rynda;' -U postgres
  - psql -c 'create extension postgis' -U postgres -d rynda
  # - python manage.py migrate --settings=Rynda.settings.travis

script:
  - python manage.py test --settings=rynda.Rynda.settings.travis

